"""
Django settings for random_walker project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
from .staging import *

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': get_secret('RDS_DB_NAME'),
#         'USER': get_secret('RDS_USERNAME'),
#         'PASSWORD': get_secret('RDS_PASSWORD'),
#         'HOST': get_secret('RDS_HOSTNAME'),
#         'PORT': get_secret('RDS_PORT'),
#     }
# }

